name: Community Contribution Label

on:
  issues:
    types: [assigned, unassigned]

jobs:
  call-label-action:
    uses: MisRob/.github/.github/workflows/community-contribution-label.yml@community-automations-updates
    secrets:
        LE_BOT_APP_ID: ${{ secrets.LE_BOT_APP_ID }}
        LE_BOT_PRIVATE_KEY: ${{ secrets.LE_BOT_PRIVATE_KEY }}
